# /
#   src
#     PingPong.API
#     PingPong.Blazor
#     PingPong.Blazor.ClientApp
#     PingPong.Blazor.ServerApp
#     PingPong.Sdk
#   test
#     PingPong.UnitTest
# ---------------------------------- temp folders below
#   packages
#     PingPong.API
#     PingPong.Blazor.ClientApp

name: Deploy full application

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'      # Supported values: [dev, test, prod]
#  push:
#    branches: [ master ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build-artifacts:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build code
      run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}
    - name: Test
      run: dotnet test --no-build --verbosity normal -c ${{ env.BUILD_CONFIGURATION }}
    - name: Publish API package
      run: |
        dotnet publish ./src/PingPong.API --no-build -c ${{ env.BUILD_CONFIGURATION }} \
          -o ./packages/PingPong.API
    - name: Publish Blazor package
      run: |
        dotnet publish ./src/PingPong.Blazor.ClientApp --no-build -c ${{ env.BUILD_CONFIGURATION }} \
          -o ./packages/PingPong.Blazor.ClientApp
    - name: Appsettings for Blazor WebAssembly app
      run: |
        cd ./packages/PingPong.Blazor.ClientApp/wwwroot
        ls
        mv appsettings.${{github.event.inputs.env}}.json appsettings.json
        mv appsettings.${{github.event.inputs.env}}.json.br appsettings.json.br
        mv appsettings.${{github.event.inputs.env}}.json.gz appsettings.json.gz
        rm appsettings.*.json*
        cd ../../..
        
    - name: Publish PingPong API artifact
      uses: actions/upload-artifact@v2
      with:
        name: pingpong-api
        path: './packages/PingPong.API'
        
    - name: Publish Blazor WebAssembly artifact
      uses: actions/upload-artifact@v2
      with:
        name: pingpong-blazor
        path: './packages/PingPong.Blazor.ClientApp/wwwroot'
        
# ------------------------------
  publish-api:
    name: Publish PingPong API
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: pingpong-api
        path: './packages/PingPong.API/'
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy PingPong.API to Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: pingpong-api-${{github.event.inputs.env}}
        package: ./packages/PingPong.API/

#    - name: Deploy static Blazor web site
#      uses: azure/CLI@v1
#      with:
#        azcliversion: 2.0.72
#        inlineScript: |
#          az storage blob upload-batch \
#            --account-name sapingpong${{github.event.inputs.env}} --auth-mode key -d '$web' \
#            -s ./packages/PingPong.Blazor.ClientApp/wwwroot
