# /
#   src
#     PingPong.API
#     PingPong.Blazor
#     PingPong.Blazor.ClientApp
#     PingPong.Blazor.ServerApp
#     PingPong.Sdk
#   test
#     PingPong.UnitTest
# ---------------------------------- temp folder s below
#   publish
#     PingPong.API
#     PingPong.Blazor.ClientApp

name: .NET

on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: pwd
      run: pwd
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}
    - name: Test
      run: dotnet test --no-build --verbosity normal -c ${{ env.BUILD_CONFIGURATION }}
    - name: dotnet publish
      run: |
        dotnet publish ./src/PingPong.API --no-build -c ${{ env.BUILD_CONFIGURATION }} \
          -o ../packages/PingPong.API
      
  publish-api:
    name: Deploy PingPong.API
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: ls /home/runner/packages/
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az webapp list --query "[?state=='Running']"
