# /
#   src
#     PingPong.API
#     PingPong.Blazor
#     PingPong.Blazor.ClientApp
#     PingPong.Blazor.ServerApp
#     PingPong.Sdk
#   test
#     PingPong.UnitTest
# ---------------------------------- temp folder s below
#   publish
#     PingPong.API
#     PingPong.Blazor.ClientApp

name: .NET

on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: pwd
      run: pwd
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}
#    - name: Test
#      run: dotnet test --no-build --verbosity normal -c ${{ env.BUILD_CONFIGURATION }}
#    - name: dotnet publish API
#      run: |
#        dotnet publish ./src/PingPong.API --no-build -c ${{ env.BUILD_CONFIGURATION }} \
#          -o ../packages/PingPong.API
    - name: dotnet publish Blazor.ClientApp
      run: |
        dotnet publish ./src/PingPong.Blazor.ClientApp --no-build -c ${{ env.BUILD_CONFIGURATION }} \
          -o ../packages/PingPong.Blazor.ClientApp
    - run: ls ../packages/PingPong.Blazor.ClientApp/
    - run: ls ../packages/PingPong.Blazor.ClientApp/PingPong.Blazor.ClientApp/
    - run: ls ../packages/PingPong.Blazor.ClientApp/PingPong.Blazor.ClientApp/dist/
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
#    - name: Deploy PingPong.API to Azure WebApp
#      uses: Azure/webapps-deploy@v2
#      with:
#        app-name: pingpong-api
#        package: ../packages/PingPong.API/

    - name: Deploy static Blazor web site
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob upload-batch \
            --account-name sapingpong --auth-mode key -d '$web' \
            -s .
     #       -s ../packages/PingPong.Blazor.ClientApp/PingPong.Blazor.ClientApp/dist/
            
#    - name: Deploy static Blazor web site
#      #id: upload
#      uses: github-developer/upload-azure-blob@v1
#      with:
#        account: sapingpong
#        destination: '$web'
#        source: ../packages/PingPong.Blazor.ClientApp/PingPong.Blazor.ClientApp/dist/
    

# c:\Projects\PingPong\publish\blazorclientapp\PingPong.Blazor.ClientApp\dist\
# ../packages/PingPong.Blazor.ClientApp/PingPong.Blazor.ClientApp/dist/

