name: Deploy Azure Infrastructure

on:  workflow_dispatch
#    inputs:
#      env:
#        description: 'Environment'
#        required: true
#        default: 'dev'      # Supported values: [dev, test, prod]

env:
  TF_IN_AUTOMATION: true
  ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}

jobs:
#  tf-dev-apply:
#    name: Deploy to Development
#    runs-on: ubuntu-latest
#    environment: development
#
#    steps:
#    - uses: actions/checkout@v2
#    - uses: hashicorp/setup-terraform@v1
#      with:
#        terraform_version: 1.0.x
#
#    - name: Run terrafrom
#      run: |
#        cd ./terraform
#        terraform init -input=false    
#        terraform workspace select dev
#        terraform apply -input=false -auto-approve
      
  tf-prod-plan:
    name: Production | TF Plan
    runs-on: ubuntu-latest
    environment: pre-production

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.x
    - name: Run terrafrom plan
      run: |
        cd ./terraform
        terraform init -input=false    
        terraform workspace select prod
        terraform plan -out tfplan
    - name: Upload 'tfplan' artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: tfplan
        path: ./terraform/tfplan
        if-no-files-found: error

  tf-prod-apply:
    name: Production | Terraform Apply
    runs-on: ubuntu-latest
    environment: production
    needs: [tf-prod-plan]
    
    steps:
    - name: Download 'tfplan'
      uses: actions/download-artifact@v2.0.10
      with:
        name: tfplan
        path: ./tfplan
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.x
    - name: Terraform Apply
      run: |
        terraform init -input=false    
        terraform workspace select prod
        terraform apply tfplan
